apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: u-5olh3zgrws
  creationTimestamp: '2024-07-05T06:51:12Z'
  finalizers:
    - wrangler.cattle.io/cloud-config-secret-remover
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
  generation: 3
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:cloudCredentialSecretName: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint: {}
          f:rkeConfig:
            .: {}
            f:chartValues: {}
            f:etcd:
              .: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:machineGlobalConfig:
              .: {}
              f:disable-apiserver: {}
              f:disable-cloud-controller: {}
              f:disable-controller-manager: {}
              f:disable-etcd: {}
              f:disable-kube-proxy: {}
              f:disable-network-policy: {}
              f:disable-scheduler: {}
              f:etcd-expose-metrics: {}
              f:secrets-encryption: {}
            f:machinePools: {}
            f:machineSelectorConfig: {}
            f:registries: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2024-07-05T06:51:12Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
        f:spec:
          f:rkeConfig:
            f:machinePoolDefaults: {}
            f:upgradeStrategy:
              f:controlPlaneDrainOptions:
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
              f:workerDrainOptions:
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
      manager: rancher-v2.8.5-secret-migrator
      operation: Update
      time: '2024-07-05T06:51:12Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:agentDeployed: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:fleetWorkspaceName: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2024-07-05T06:54:39Z'
  name: test
  namespace: fleet-default
  resourceVersion: '5892260'
  uid: 2abd0752-a4fa-4990-8501-e3e8e4f69621
spec:
  cloudCredentialSecretName: cattle-global-data:cc-w48ww
  kubernetesVersion: v1.28.10+k3s1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      disable-apiserver: false
      disable-cloud-controller: false
      disable-controller-manager: false
      disable-etcd: false
      disable-kube-proxy: false
      disable-network-policy: false
      disable-scheduler: false
      etcd-expose-metrics: false
      secrets-encryption: false
    machinePoolDefaults: {}
    machinePools:
      - controlPlaneRole: true
        drainBeforeDelete: true
        dynamicSchemaSpec: >-
          {"resourceFields":{"cloudConfig":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"just
          keep it empty, this value will be filled by
          rancher-machine"},"clusterId":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          cluster
          id"},"clusterType":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          cluster
          type"},"cpuCount":{"type":"string","default":{"stringValue":"2","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"number
          of CPUs for
          machine"},"diskBus":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"bus
          of disk for
          machine"},"diskInfo":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          disk
          info"},"diskSize":{"type":"string","default":{"stringValue":"0","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"size
          of disk for machine (in
          GiB)"},"enableEfi":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable
          vm
          efi"},"enableSecureBoot":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable
          vm secure boot, only works when enable
          efi"},"imageName":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          image
          name"},"keyPairName":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          key pair
          name"},"kubeconfigContent":{"type":"password","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"contents
          of kubeconfig file for harvester cluster, base64 is
          supported"},"memorySize":{"type":"string","default":{"stringValue":"4","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"size
          of memory for machine (in
          GiB)"},"networkData":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"networkData
          content of cloud-init for machine, base64 is
          supported"},"networkInfo":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          network
          info"},"networkModel":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          network
          model"},"networkName":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          network
          name"},"networkType":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          network
          type"},"sshPassword":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH
          password"},"sshPort":{"type":"string","default":{"stringValue":"22","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH
          port"},"sshPrivateKeyPath":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH
          private key path
          "},"sshUser":{"type":"string","default":{"stringValue":"root","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH
          username"},"userData":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"userData
          content of cloud-init for machine, base64 is
          supported"},"vgpuInfo":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester-vgpu-info"},"vmAffinity":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          vm affinity, base64 is
          supported"},"vmNamespace":{"type":"string","default":{"stringValue":"default","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"harvester
          vm namespace"}}}
        etcdRole: true
        machineConfigRef:
          kind: HarvesterConfig
          name: nc-test-pool1-6fgwl
        name: pool1
        quantity: 3
        unhealthyNodeTimeout: 0s
        workerRole: true
    machineSelectorConfig:
      - config:
          docker: false
          protect-kernel-defaults: false
          selinux: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  agentDeployed: true
  clientSecretName: test-kubeconfig
  clusterName: c-m-svwh7tf9
  conditions:
    - lastUpdateTime: '2024-07-05T06:54:39Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2024-07-05T06:51:12Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2024-07-05T06:54:39Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2024-07-05T06:54:35Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2024-07-05T06:51:12Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2024-07-05T06:51:12Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2024-07-05T06:51:12Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2024-07-05T06:51:12Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2024-07-05T06:51:12Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2024-07-05T06:54:35Z'
      message: >-
        non-ready bootstrap machine(s) test-pool1-6cd785976bxqs8ch-hrqnh and
        join url to be available on bootstrap node
      reason: Waiting
      status: Unknown
      type: Updated
    - lastUpdateTime: '2024-07-05T06:54:35Z'
      message: >-
        non-ready bootstrap machine(s) test-pool1-6cd785976bxqs8ch-hrqnh and
        join url to be available on bootstrap node
      reason: Waiting
      status: Unknown
      type: Provisioned
    - lastUpdateTime: '2024-07-05T06:54:35Z'
      message: >-
        non-ready bootstrap machine(s) test-pool1-6cd785976bxqs8ch-hrqnh and
        join url to be available on bootstrap node
      reason: Waiting
      status: Unknown
      type: Ready
    - lastUpdateTime: '2024-07-05T06:51:13Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2024-07-05T06:51:13Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2024-07-05T06:51:13Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2024-07-05T06:51:13Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2024-07-05T06:51:13Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2024-07-05T06:51:13Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2024-07-05T06:54:35Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2024-07-05T06:54:25Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2024-07-05T06:54:25Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2024-07-05T06:54:26Z'
      status: 'True'
      type: AgentDeployed
    - lastUpdateTime: '2024-07-05T06:54:39Z'
      status: 'True'
      type: Waiting
  fleetWorkspaceName: fleet-default
  observedGeneration: 3
  ready: true
