apiVersion: "meta.k8s.appscode.com/v1alpha1"
kind: "ResourceCalculator"
request: 
  resource: 
    apiVersion: "kubedb.com/v1alpha2"
    kind: "FerretDB"
    metadata: 
      labels: 
        app.kubernetes.io/instance: "rafi"
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/name: "ferretdbs.kubedb.com"
      name: "rafi"
      namespace: "demo"
    spec: 
      deletionPolicy: "WipeOut"
      monitor: 
        agent: "prometheus.io/operator"
        prometheus: 
          exporter: 
            resources: 
              requests: 
                cpu: "100m"
                memory: "128Mi"
          serviceMonitor: 
            interval: "30s"
            labels: 
      replicas: 3
      podTemplate:
        spec: 
          containers: 
          - name: "ferretdb"
            resources: 
              limits: 
                cpu: "1"
                memory: "1024Mi"
          nodeSelector: 
            app: "ferretdbs.kubedb.com"
            instance: "rafi"
            namespace: "demo"
            nodepool: "standard-bsv2-family"
          podPlacementPolicy: 
            name: "default"
          tolerations: 
          - effect: "NoSchedule"
            key: "app"
            operator: "Equal"
            value: "ferretdbs.kubedb.com"
          - effect: "NoSchedule"
            key: "instance"
            operator: "Equal"
            value: "rafi"
          - effect: "NoSchedule"
            key: "namespace"
            operator: "Equal"
            value: "demo"
          - effect: "NoSchedule"
            key: "nodepool"
            operator: "Equal"
            value: "standard-bsv2-family"
      sslMode: "requireSSL"
      storage: 
        accessModes: 
        - "ReadWriteOnce"
        resources: 
          requests: 
            storage: "10Gi"
        storageClassName: "default"
      storageType: "Durable"
      tls: 
        issuerRef: 
          apiGroup: "cert-manager.io"
          kind: "ClusterIssuer"
          name: "cluster-issuer"
      version: "1.18.0"
  edit: false