apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    app.kubernetes.io/component: kubedb
    app.kubernetes.io/instance: opscenter-datastore
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: featuresets.ui.k8s.appscode.com
    app.kubernetes.io/part-of: opscenter-datastore
  name: kubedb
  namespace: kubeops
spec:
  chart:
    spec:
      chart: kubedb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
      version: v2023.11.2
  dependsOn:
  - name: license-proxyserver
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  releaseName: kubedb
  storageNamespace: kubedb
  targetNamespace: kubedb
  timeout: 30m
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    global:
      registryFQDN: ghcr.io
      license:
        -----BEGIN CERTIFICATE-----
        MIIEVjCCAz6gAwIBAgIIQtvVvBtj0JYwDQYJKoZIhvcNAQELBQAwJTEWMBQGA1UE
        ChMNQXBwc0NvZGUgSW5jLjELMAkGA1UEAxMCY2EwHhcNMjMxMjIyMDQyNzM3WhcN
        MjQwMTIxMDQyNzM3WjCCARgxDzANBgNVBAYTBmt1YmVkYjETMBEGA1UECBMKZW50
        ZXJwcmlzZTGBpDAXBgNVBAoTEGt1YmVkYi1jb21tdW5pdHkwFwYDVQQKExBrdWJl
        ZGItZXh0LXN0YXNoMBgGA1UEChMRa3ViZWRiLWF1dG9zY2FsZXIwGAYDVQQKExFr
        dWJlZGItZW50ZXJwcmlzZTAcBgNVBAoTFXBhbm9wdGljb24tZW50ZXJwcmlzZTAe
        BgNVBAoTF2t1YmVkYi1tb25pdG9yaW5nLWFnZW50MRowGAYDVQQLExFrdWJlZGIt
        ZW50ZXJwcmlzZTEtMCsGA1UEAxMkMjU4OTRjY2QtYjczMS00MGZmLTg3ZjktZTQy
        M2Q1YzlmYmIxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv1jOl1qg
        SqXUJDYTDOHFo+kOu6h/g5wgTgGhQJjIbCQ3bf90nXOxLMXgGpj472JQAq1oKsDl
        FzUZpVln8Qk5L9SequK0iaY9MJc5DlzgmGKtCimTOA1/YWLnrcSuO18JricVTykJ
        uqllTia95j3i82DHCuo0r9bzxmudGCw0X13vxIGNPaaG6a3tzggryigZpmER2OzF
        +5RVCuep440i9mluNaGa6cW5k1Eu4jphsOjAmVNrn/7JEiGjfu84jnX+ZT1CeDBN
        +pxFIgAqsbUnPR/iYIu7Euuivwb9H/OriFgf4JV6uwjetwrOhB5jawO7/1LAJB4A
        fzacpZOoRkaUZQIDAQABo4GUMIGRMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
        BggrBgEFBQcDAjBqBgNVHREEYzBhgiQyNTg5NGNjZC1iNzMxLTQwZmYtODdmOS1l
        NDIzZDVjOWZiYjGBJUFybm9iIGt1bWFyIHNhaGEgPGFybm9iQGFwcHNjb2RlLmNv
        bT6BEmFybm9iQGFwcHNjb2RlLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAs2j6sAb3
        VGiyG+UofJcsA7PzL5pVZGUwV7w4IFub7ucFurb3FYmCwaBR8nQymrFbovNWF52z
        nN7jV3C0+Tm1kambIDGeU4y+ADDtCFTtJdppp5zmwvlepqfjalrASFDM4/iqyGY9
        SDio94C28RsKzyQudP4JBYpqvZNe2SrsCydMSWJwwsSsy1S67oMMihNURStp+pJs
        OQR89X3bdfaWBnvElhdTW/qosIhJrDbxdWPXl6aWuKVvYD4OlJa/BA6JP/dCEbTw
        U/zKp0qrcEbHyI35J0//z7yjEwlQP6ImBMlNDhPuIgOYRJF4jd4NdnY4uBGEzf0t
        kRPtuFIBVLPFcQ==
        -----END CERTIFICATE-----
    kubedb-autoscaler:
      enabled: true
    kubedb-catalog:
      enabled: true
      proxies:
        appscode: r.appscode.com
        dockerHub: ""
        dockerLibrary: ""
        ghcr: ghcr.io
        kubernetes: registry.k8s.io
        quay: quay.io
    kubedb-dashboard:
      enabled: true
    kubedb-metrics:
      enabled: false
    kubedb-ops-manager:
      enabled: true
    kubedb-provisioner:
      enabled: true
    kubedb-schema-manager:
      enabled: true