allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: prepare-cluster
    meta.helm.sh/release-namespace: default
  name: updated-rwo
mountOptions:
- noatime
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: xfs
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
