apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: try
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example
        image: nginx:latest
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: "updated-rwo"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi