resources:
  - postgres

dashboard:
  folderID: 0
  overwrite: true
  alerts: true
  replacements:
    job=\"kube-state-metrics\": job=\"kubernetes-service-endpoints\"
    job=\"kubelet\": job=\"kubernetes-nodes-cadvisor\"
    job=\"$app-stats\": job=\"kubedb-databases\"





grafana:
  # Name of Grafana Appbinding where these dashboards are applied
  # name: ""
  # Namespace of Grafana Appbinding where these dashboards are applied
  # namespace: ""
  version: 8.0.7
  url: "http://grafana.monitoring.svc:80"
  apikey: "eyJrIjoiUVk5bkZjWFBjNk9GSGU0elVTZU5DSlZTUTdqbnBTNFMiLCJuIjoiYXJub2IiLCJpZCI6MX0="

app:
  name: built
  namespace: gg


# curl -H "Authorization: Bearer eyJrIjoiQTQ5NEM5MDI0OUR6TnEyNU1wSElvUFdxcHFXZDR6SVkiLCJuIjoiYXJub2IiLCJpZCI6MX0=" http://localhost:9091/api/dashboards/home