# export KUBECONFIG=/home/arnob/Downloads/prometheus-operator-kubeconfig.yaml


# Default values for kubedb-grafana-dashboards.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""

# List of resources for which dashboards will be applied
resources: # +doc-gen:break
  - mongodb
#  - elasticsearch
#  - kafka
#  - mariadb
#  - mongodb
#  - mysql
#  - perconaxtradb
#  - postgres
#  - proxysql
#  - redis

dashboard:
  # ID of Grafana folder where these dashboards will be applied
  folderID: 0
  # If true, dashboard with matching uid will be overwritten
  overwrite: true
  templatize:
    # If true, datasource will be prefixed to dashboard name
    title: false
    # If true, datasource will be hardcoded in the dashboard
    datasource: false
  alerts: true
  replacements: {}
    # job=\"kube-state-metrics\": job=\"kubernetes-service-endpoints\"
    # job=\"kubelet\": job=\"kubernetes-nodes-cadvisor\"
    # job=\"$app-stats\": job=\"kubedb-databases\"

grafana:
  # Name of Grafana Appbinding where these dashboards are applied
  name: ""
  # Namespace of Grafana Appbinding where these dashboards are applied
  namespace: ""
  version: 8.0.7
  # builtin
  # url: "http://grafana.monitoring.svc:80"
  # apikey: "eyJrIjoiS1pieXlFRVlyWUxnSjVaVUFYc21tMXVNNGpERmlubkMiLCJuIjoiYXJub2IiLCJpZCI6MX0="
  # operator
  url: "http://prometheus-grafana.monitoring.svc:80"
  apikey: "eyJrIjoiZGlaaWZEYTNkSkJVQWgwOTFoaUNoTHF2dTBRMlFtaEciLCJuIjoiYXJub2IiLCJpZCI6MX0="

app:
  name: mg4
  namespace: demo


# curl -H "Authorization: Bearer eyJrIjoiQTQ5NEM5MDI0OUR6TnEyNU1wSElvUFdxcHFXZDR6SVkiLCJuIjoiYXJub2IiLCJpZCI6MX0=" http://localhost:9091/api/dashboards/home