
resources:
  - mongodb

dashboard:
  folderID: 0
  overwrite: true
  alerts: true
  replacements:
    job=\"kube-state-metrics\": job=\"kubernetes-service-endpoints\"
    job=\"kubelet\": job=\"kubernetes-nodes-cadvisor\"
    job=\"$app-stats\": job=\"kubedb-databases\"

grafana:
  version: 8.0.7
  url: "http://grafana.monitoring.svc:80"
  apikey: "eyJrIjoiNXZWRjdscWF1S2cwc1BXMEJYVTFRMnRHdk1QVzltSTAiLCJuIjoibXkiLCJpZCI6MX0="

app:
  name: "mg"
  namespace: "demo"

# curl -H "Authorization: Bearer eyJrIjoiNXZWRjdscWF1S2cwc1BXMEJYVTFRMnRHdk1QVzltSTAiLCJuIjoibXkiLCJpZCI6MX0=" http://localhost:9091/api/dashboards/home
