resources:
  - postgres

dashboard:
  folderID: 0
  overwrite: true
  alerts: true
  replacements: 
    job=\"kube-state-metrics\": job=\"kubernetes-service-endpoints\"
    job=\"kubelet\": job=\"kubernetes-nodes-cadvisor\"
    job=\"$app-stats\": job=\"kubedb-databases\"

# grafana:
#   version: 7.5.5
#   url: "http://prometheus-grafana.monitoring.svc:80"
#   apikey: "eyJrIjoiSDdPaGd2NkpHODJuMlZsb3RMclk5aHFVWjYzUnRIQzEiLCJuIjoic291cmF2IiwiaWQiOjF9"

grafana:
  version: 8.0.7
  url: "http://grafana.monitoring.svc:80"
  apikey: "eyJrIjoiMExmNDQwcnAzMlhEMGw1ZXB4b0hmTEtRZUY2UUlJRmkiLCJuIjoiZGVtbyIsImlkIjoxfQ=="

app:
  name: built
  namespace: gg
# "eyJrIjoiSDdPaGd2NkpHODJuMlZsb3RMclk5aHFVWjYzUnRIQzEiLCJuIjoic291cmF2IiwiaWQiOjF9"
# "definition": "label_values(kube_namespace_labels,namespace)",
# "definition": "query_result(kubedb_com_postgres_created{namespace=\"$namespace\"})",
# count(pg_replication_is_replica{job="kubedb-databases",namespace="demo"} == 0)