apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubedb.com/v1alpha2","kind":"MongoDB","metadata":{"annotations":{},"name":"mongo","namespace":"mongo"},"spec":{"arbiter":{"podTemplate":{"spec":{"resources":{"requests":{"cpu":"200m","memory":"200Mi"}}}}},"monitor":{"agent":"prometheus.io/operator","prometheus":{"exporter":{"securityContext":{"allowPrivilegeEscalation":false,"runAsUser":2000}},"serviceMonitor":{"interval":"10s","labels":{"release":"prometheus"}}}},"serviceTemplates":[{"alias":"primary","metadata":{"annotations":{"external-dns.alpha.kubernetes.io/hostname":"mongo.vyrl.co","service.beta.kubernetes.io/aws-load-balancer-internal":"true","service.beta.kubernetes.io/aws-load-balancer-ssl-cert":"arn:aws:acm:us-west-2:422025336571:certificate/632de120-404f-4226-9204-a872319fb995","service.beta.kubernetes.io/aws-load-balancer-ssl-ports":"https","service.beta.kubernetes.io/aws-load-balancer-target-group-attributes":"deregistration_delay.timeout_seconds=5","service.beta.kubernetes.io/aws-load-balancer-type":"nlb-ip"}},"spec":{"ports":[{"name":"primary","nodePort":30006,"port":27017}],"type":"LoadBalancer"}}],"shardTopology":{"configServer":{"replicas":2,"storage":{"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"gp2"}},"mongos":{"replicas":2},"shard":{"podTemplate":{"spec":{"resources":{"requests":{"cpu":"2","memory":"8Gi"}}}},"replicas":2,"shards":1,"storage":{"resources":{"requests":{"storage":"300Gi"}},"storageClassName":"gp2"}}},"terminationPolicy":"WipeOut","version":"4.4.6"}}
  creationTimestamp: "2023-08-03T21:28:12Z"
  generation: 1
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mongo
  namespace: mongo
  ownerReferences:
  - apiVersion: kubedb.com/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: MongoDB
    name: mongo
    uid: f195485d-b2ae-4009-b469-165d3569786b
  resourceVersion: "1364119246"
  uid: 0d760aae-1038-4789-b986-d9992a3becad
spec:
  appRef:
    apiGroup: kubedb.com
    kind: MongoDB
    name: mongo
    namespace: mongo
  clientConfig:
    service:
      name: mongo
      port: 27017
      scheme: mongodb
  parameters:
    apiVersion: config.kubedb.com/v1alpha1
    configServer: cnfRepSet/mongo-configsvr-0.mongo-configsvr-pods.mongo.svc:27017,mongo-configsvr-1.mongo-configsvr-pods.mongo.svc:27017
    kind: MongoConfiguration
    replicaSets:
      host-0: shard0/mongo-shard0-0.mongo-shard0-pods.mongo.svc:27017,mongo-shard0-1.mongo-shard0-pods.mongo.svc:27017,mongo-shard0-arbiter-0.mongo-shard0-pods.mongo.svc:27017
    stash:
      addon:
        backupTask:
          name: mongodb-backup-4.4.6
        restoreTask:
          name: mongodb-restore-4.4.6
  secret:
    name: mongo-auth
  type: kubedb.com/mongodb
  version: 4.4.6