apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: pg-demo
  namespace: demo
spec:
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: Delete
  podTemplate:
    spec:
      resources:
        requests:
          cpu: 600m
          memory: 600Mi
  coordinator:
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
  version: "15.5"