apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: as
  namespace: demo
spec:
  databaseRef:
    name: repl4
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    replicaSet:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
      # controlledResources: ["cpu", "memory"]
      # containerControlledValues: "RequestsAndLimits"
    nodeTopology:
      name: standard-basv2-family