# kubectl create secret generic gcp-secret -n crossplane-system --from-file=creds=./gcp-credentials.json

apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: appscode-testing
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-secret
      key: creds