apiVersion: policy.k8s.appscode.com/v1alpha1
kind: PolicyReport
request:
  ref:
    name: kubedb-kubedb-provisioner
    namespace: kubedb
  resource:
    group: apps
    kind: Deployment
    name: deployments
    version: v1
response:
  constraints:
  - auditTimestamp: "2023-03-02T06:05:40Z"
    name: container-must-have-requests
    violations:
    - enforcementAction: warn
      group: ""
      kind: Pod
      message: container <operator> has no resource requests
      name: kubedb-kubedb-provisioner-75dfd7d599-mpprq
      namespace: kubedb
      version: v1
  - auditTimestamp: "2023-03-02T06:05:40Z"
    name: replica-limits
    violations:
    - enforcementAction: deny
      group: apps
      kind: Deployment
      message: 'The provided number of replicas is not allowed for deployment: kubedb-kubedb-provisioner.
        Allowed ranges: {"ranges": [{"max_replicas": 50, "min_replicas": 3}]}'
      name: kubedb-kubedb-provisioner
      namespace: kubedb
      version: v1
