apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: db-backup
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MongoDB
    namespace: demo
    name: standalone
  backends:
    - name: linode-backend
      storageRef:
        apiGroup: storage.kubestash.com
        namespace: demo
        kind: BackupStorage
        name: linode
      retentionPolicy:
        name: rp
        namespace: demo
  sessions:
    - name: frequent-backup
      sessionHistoryLimit: 3
      scheduler:
        schedule: "*/2 * * * *"
        successfulJobsHistoryLimit: 10
        failedJobsHistoryLimit: 10
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: linode-repo
          backend: linode-backend
          directory: /full
          encryptionSecret:
           name: encrypt-secret # some addon may not support encryption
           namespace: demo
      addon:
        name: mongodb-backup-restore-addon
        tasks:
          - name: mongodb-backup-task
# NB: Deleting the backupConfiguration will delete not delete the created repositories & snapshots