apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: restore-mongodb
  namespace: demo
spec:
  version: "4.4.6"
  replicaSet:
    name: "rs0"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: "linode-block-storage"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
