apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MongoDB
    namespace: demo
    name: restore
  # manifestOptions:
  #   restoreNamespace: demo2
  #   mongoDB:
  #     db: true
  #     dbName: new-mongodb
  #     authSecret: true
  #     configSecret: true
  dataSource:
    snapshot: linode-repo-db-backup-wow-backup-1708423800 
    repository: linode-repo
    encryptionSecret:
      name: encrypt-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: mongodb-addon
    tasks:
      - name: logical-backup-restore