apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: kubeops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: arnobkumarsaha/private-test:01
        name: private-test
      imagePullSecrets: 
      - name: pull-secret
