apiVersion: scanner.appscode.com/v1alpha1
kind: ImageScanRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"scanner.appscode.com/v1alpha1","kind":"ImageScanRequest","metadata":{"annotations":{},"name":"private-123"},"spec":{"image":"arnobkumarsaha/private-test:01","namespace":"kubeops","pullSecrets":[{"name":"pull-secret"}],"serviceAccountName":"panopticon"}}
  creationTimestamp: "2023-01-20T12:25:55Z"
  generation: 1
  name: private-123
  resourceVersion: "110096"
  uid: e880913e-6c9d-4f3f-b6ca-9c9544499c72
spec:
  image: arnobkumarsaha/private-test:01
  namespace: kubeops
  pullSecrets:
  - name: pull-secret
  serviceAccountName: panopticon
status:
  image:
    name: arnobkumarsaha/private-test:01
    tag: "01"
    visibility: Private
  jobName: scan-image-28ffca3353cac4b017e3e08507031929
  phase: Current
  reportRef:
    lastChecked: "2023-01-20T12:26:04.83844908Z"
    name: 91edbd25c55ca35a98c252e2868ec562
