apiVersion: v1
kind: Pod
metadata:
  name: busy
  namespace: demo
spec:
  containers:
  - name: cont
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - "3600"
    # volumeMounts:
    # - name: datadir
    #   mountPath: /data/db
  # volumes:
  # - name: datadir
  #   persistentVolumeClaim:
  #     claimName: datadir-rs-1