apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xx
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      nodeName: lke148540-218049-56079bea0000
      containers:
      - name: ee
        image: arnobkumarsaha/perm
        args: ["/bin/sh", "-c", "sleep 30000"]
        volumeMounts:
        # - name: data
        #   mountPath: /data
        - name: hello
          mountPath: /hello
        - name: empty
          mountPath: /empty
        # - name: test
        #   mountPath: /test
          # readOnly: true
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      securityContext:
        fsGroup: 1000
      # tolerations:
      # - effect: NoSchedule
      #   key: nodepool
      #   operator: Equal
      #   value: medium
      # nodeSelector:
      #   cloud.google.com/gke-nodepool: medium
      volumes:
      - name: hello
        nfs:
          path: /exports
          server: 10.128.182.254
      - name: empty
        emptyDir: {}
      # - name: test
      #   persistentVolumeClaim: 
      #     claimName: my-pvc
  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #   spec:
  #     accessModes: [ "ReadOnlyMany" ]
  #     # storageClassName: linode-block-storage-retain
  #     resources:
  #       requests:
  #         storage: 1Gi
