apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      # initContainers:
      # - name: ii
      #   image: ubuntu
      #   args: ["/bin/sh", "-c", "chmod -R 440 /data"]
      #   volumeMounts:
      #   - name: data
      #     mountPath: /data
      #   securityContext:
      #     runAsUser: 65534
      #     runAsGroup: 65534
      containers:
      - name: ee
        image: arnobkumarsaha/perm
        args: ["/bin/sh", "-c", "sleep 30000"]
        # resources:
        #   requests:
        #     memory: "100Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "300Mi"
        #     cpu: "300m"
        volumeMounts:
        - name: data
          mountPath: /data
          # readOnly: true
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      securityContext:
        fsGroup: 1000
      # tolerations:
      # - effect: NoSchedule
      #   key: nodepool
      #   operator: Equal
      #   value: medium
      # nodeSelector:
      #   cloud.google.com/gke-nodepool: medium
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadOnlyMany" ]
      # storageClassName: linode-block-storage-retain
      resources:
        requests:
          storage: 1Gi
