apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: specific-restore-db
  namespace: demo
spec:
  version: "4.4.26"
  replicaSet:
    name: "rs0"
  replicas: 3
  storageType: Durable
  init:
    waitForInitialRestore: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
---
apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: specific-restore
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MongoDB
    namespace: demo
    name: specific-restore-db
  dataSource:
    snapshot: specific-repo-db-backup-specific-db-1709815140 
    repository: specific-repo
    encryptionSecret:
      name: encrypt-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: mongodb-addon
    tasks:
    - name: logical-backup-restore
      params:
        args: --db=testdb