apiVersion: kubedb.com/v1alpha2
kind: MariaDB
metadata:
  name: maria
  namespace: demo
spec:
  replicas: 3
  podTemplate:
    spec:
      resources:
        requests:
          cpu: 555m
          memory: 555Mi
  coordinator:
    resources:
      requests:
        cpu: 222m
        memory: 222Mi
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: Delete
  version: 11.1.3