# apiVersion: kubedb.com/v1alpha2
# kind: MongoDB
# metadata:
#   name: mg6
#   namespace: demo
# spec:
#   version: "6.0.12"
#   terminationPolicy: WipeOut
#   replicas: 3
#   replicaSet:
#     name: "rs1"
#   podTemplate:
#     spec:
#       resources:
#         requests:
#           cpu: 888m
#           memory: 888Mi
#   coordinator:
#     resources:
#       requests:
#         cpu: 222m
#         memory: 222Mi
#   storage:
#     accessModes:
#     - ReadWriteOnce
#     resources:
#       requests:
#         storage: 2Gi
---
apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mg6
  namespace: demo
spec:
  version: "6.0.12"
  deletionPolicy: WipeOut
  replicas: 3
  replicaSet:
    name: "rs1"
  podTemplate:
    spec:
      containers:
      - name: "mognodb"
        resources:
          requests:
            cpu: 888m
            memory: 888Mi
      - name: mg-coordinator
        resources:
          requests:
            cpu: 222m
            memory: 222Mi
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
