apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg6
  namespace: demo
spec:
  allowedSchemas:
    namespaces:
      from: Selector
      selector:
        matchExpressions:
        - {key: kubernetes.io/metadata.name, operator: In, values: [dev]}
    selector:
      matchLabels:
        "schema.kubedb.com": "mongo"
  version: "6.0.5"
  terminationPolicy: WipeOut
  replicas: 3
  replicaSet:
    name: "rs"
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  # serviceTemplates:
  # - alias: primary
  #   metadata: {}
  #   spec:
  #     ports:
  #     - name: db
  #       nodePort: 30003
  #       port: 27017
  #     type: LoadBalancer
  # hidden:
  #   podTemplate:
  #     spec:
  #       resources:
  #         requests:
  #           cpu: "400m"
  #           memory: "400Mi"
  #   replicas: 1
  #   storage:
  #     # storageClassName: "longhorn"
  #     accessModes:
  #       - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 2Gi
  # arbiter:
  #   podTemplate: {}
  # configSecret:
  #   name: mg-configuration
  # sslMode: preferSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer
  # clusterAuthMode: x509
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
        interval: 10s


# sudo apt-get install -y 
# mongodb-org=<version> 
# mongodb-org-database=<version> 
# mongodb-org-server=<version> 
# mongodb-org-shell=<version> 
# mongodb-org-mongos=<version> 
# mongodb-org-tools=<version>
