apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-restore
  namespace: demo
spec:
  version: "4.2.3"
  terminationPolicy: WipeOut
  replicas: 3
  replicaSet:
    name: "rs"
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #       interval: 10s
