# apiVersion: kubedb.com/v1alpha2
# kind: Postgres
# metadata:
#   name: pgc
#   namespace: demo
# spec:
#   replicas: 1
#   podTemplate:
#     spec:
#       initContainers:
#       - name: postgres-init-container
#         securityContext:
#           runAsGroup: 1000660000
#           runAsUser: 1000660000
#           capabilities:
#             drop:
#             - ALL
#           runAsNonRoot: true
#           seccompProfile:
#             type: RuntimeDefault
#       containerSecurityContext:
#         runAsGroup: 1000660000
#         runAsUser: 1000660000
#         allowPrivilegeEscalation: false
#         capabilities:
#           drop:
#           - ALL
#         runAsNonRoot: true
#         seccompProfile:
#           type: RuntimeDefault
#   storage:
#     accessModes:
#     - ReadWriteOnce
#     resources:
#       requests:
#         storage: 1Gi
#     # storageClassName: standard
#   storageType: Durable
#   terminationPolicy: WipeOut
#   version: "15.5-bookworm"
---
apiVersion: kubedb.com/v1
kind: Postgres
metadata:
  name: pgc
  namespace: demo
spec:
  replicas: 1
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: default
  storageType: Durable
  deletionPolicy: WipeOut
  version: "15.5-bookworm"
