apiVersion: kubedb.com/v1
kind: Postgres
metadata:
  name: pg-demo
  namespace: demo
spec:
  # replicas: 1
  # podTemplate:
  #   spec:
  #     resources:
  #       requests:
  #         cpu: 555m
  #         memory: 555Mi
  # coordinator:
  #   resources:
  #     requests:
  #       cpu: 222m
  #       memory: 222Mi
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    # storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  version: "15.5"