apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: built
  namespace: gg
spec:
  version: "15.5"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: "longhorn"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Delete
  monitor:
    agent: prometheus.io/builtin
