apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: as
  namespace: demo
spec:
  databaseRef:
    name: mg-rs
  storage:
    replicaSet:
      trigger: "On"
      usageThreshold: 20
      scalingThreshold: 30
