apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: sh
  namespace: demo
spec:
  version: "4.4.6"
  storageType: Durable
  shardTopology:
    configServer:
      storage:
        # storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
      replicas: 2
      # podTemplate:
      #   spec:
      #     resources:
      #       requests:
      #         "cpu": 0.5
      #         "memory": 500Mi
    mongos:
      replicas: 2
    shard:
      storage:
        # storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
      replicas: 2
      shards: 2
      podTemplate:
        spec:
          resources:
            requests:
              "cpu": 0.5
              "memory": 500Mi
            limits:
              "cpu": 0.8
              "memory": 1Gi
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  # hidden:
  #   podTemplate: {}
  #   replicas: 1
  #   storage:
  #     accessModes:
  #       - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 1Gi
  # arbiter:
  #   podTemplate: {}
  terminationPolicy: WipeOut
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer
  # clusterAuthMode: x509
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #       interval: 10s
  # monitor:
  #   agent: prometheus.io/builtin
