apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: s6
  namespace: demo
spec:
  version: "6.0.5"
  terminationPolicy: WipeOut
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  sslMode: requireSSL
  tls:
    issuerRef:
      apiGroup: "cert-manager.io"
      kind: Issuer
      name: mongo-ca-issuer
  clusterAuthMode: x509
  # configSecret:
  #   name: mg-custom-config


# > restoreSession
# nil

# > restore job
# app.kubernetes.io/managed-by=kubestash.com,
# kubestash.com/invoker-name=sample,
# kubestash.com/invoker-namespace=demo

# app.kubernetes.io/component=kubestash-restore,
# app.kubernetes.io/managed-by=kubestash.com,
# kubestash.com/invoker-name=sample,
# kubestash.com/invoker-namespace=demo
