global:
  featureGates:
    ClickHouse: true
    Druid: true
    Elasticsearch: true
    FerretDB: true
    Kafka: true
    MariaDB: true
    Memcached: true
    MongoDB: true
    MSSQLServer: true
    MySQL: true
    PerconaXtraDB: true
    PgBouncer: true
    Pgpool: true
    Postgres: true
    ProxySQL: true
    RabbitMQ: true
    Redis: true
    Singlestore: true
    Solr: true
    ZooKeeper: true