apiVersion: kubedb.com/v1alpha2
kind: ZooKeeper
metadata:
  name: zk-demo
  namespace: demo
spec:
  deletionPolicy: WipeOut
  replicas: 1
  storage:
    resources:
      requests:
        storage: 1Gi
  version: 3.9.1
---
apiVersion: kubedb.com/v1alpha2
kind: ZooKeeper
metadata:
  labels:
    app.kubernetes.io/instance: my
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zooKeepers.kubedb.com
  name: my
  namespace: demo
spec:
  deletionPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      serviceMonitor:
        interval: 30s
        labels: {}
  podTemplate:
    spec:
      containers:
      - name: zookeeper
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
      nodeSelector:
        app: zookeepers.kubedb.com
        instance: my
        namespace: demo
        nodepool: standard-bsv2-family
      podPlacementPolicy:
        name: default
      tolerations:
      - effect: NoSchedule
        key: app
        operator: Equal
        value: zookeepers.kubedb.com
      - effect: NoSchedule
        key: instance
        operator: Equal
        value: my
      - effect: NoSchedule
        key: namespace
        operator: Equal
        value: demo
      - effect: NoSchedule
        key: nodepool
        operator: Equal
        value: standard-bsv2-family
  replicas: 3
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: default
  storageType: Durable
  version: 3.8.3
