apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: compute
  namespace: demo
spec:
  databaseRef:
    name: simple
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    replicaSet:
      trigger: "On"
      # podLifeTimeThreshold: 5m
      # resourceDiffPercentage: 200
      minAllowed:
        cpu: 470m
        memory: 1.4Gi
      maxAllowed:
        cpu: 7900m
        memory: 29Gi
      controlledResources: ["cpu", "memory"]
      containerControlledValues: "RequestsAndLimits"
    nodeTopology:
      name: gke-pools

