# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-kube-prometheus-prometheus
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "51.9.4"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-51.9.4
    release: "prometheus"
    heritage: "Helm"
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: prometheus-kube-prometheus-alertmanager
        port: http-web
        pathPrefix: "/"
        apiVersion: v2
  image: "quay.io/prometheus/prometheus:v2.47.1"
  version: v2.47.1
  externalUrl: http://prometheus-kube-prometheus-prometheus.monitoring:9090
  paused: false
  replicas: 1
  shards: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  tsdb:
    outOfOrderTimeWindow: 0s
  walCompression: true
  routePrefix: "/"
  serviceAccountName: prometheus-kube-prometheus-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: "prometheus"

  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "prometheus"

  podMonitorNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: "prometheus"

  probeNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: "prometheus"

  scrapeConfigSelector:
    matchLabels:
      release: "prometheus"

  scrapeConfigNamespaceSelector: {}
  portName: http-web
  hostNetwork: false
---

