apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: compute
  namespace: demo
spec:
  databaseRef:
    name: simple
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    replicaSet:
      trigger: "On"
      podLifeTimeThreshold: 5m
      resourceDiffPercentage: 100
      minAllowed:
        cpu: "1"
        memory: 1900Mi
      maxAllowed:
        cpu: 6
        memory: 16Gi
      controlledResources: ["cpu", "memory"]
      containerControlledValues: "RequestsAndLimits"
    nodeTopology:
      name: lke-pools
      scaleUpDiffPercentage: 10
      scaleDownDiffPercentage: 25


# "uncappedTarget": {
#   "cpu": "1168m",
#   "memory": "3861631195"
# }
# 110%

# I1225 19:02:31.896134       1 nodepool.go:107] midPoints =====> 
# I1225 19:02:31.896139       1 nodepool.go:126] 0  0-- 1020054733 
# I1225 19:02:31.896144       1 nodepool.go:126] 1  1000-- 3113851290 
# I1225 19:02:31.896149       1 nodepool.go:126] 2  3000-- 6388763853 
# I1225 19:02:31.896152       1 nodepool.go:126] 3  5000-- 12884901888 
