apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: simple
  namespace: demo
spec:
  version: "4.4.26"
  terminationPolicy: WipeOut
  replicas: 3
  replicaSet:
    name: "rs"
  podTemplate:
    spec:
      nodeSelector:
        beta.kubernetes.io/instance-type: g6-standard-1
      # tolerations:
      # - key: nodepool
      #   value: medium
      #   effect: NoSchedule
      resources:
        requests:
          "cpu": 500m
          "memory": 1.5Gi
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

# beta.kubernetes.io/instance-type=g6-standard-2 (1/2/4/6)