apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: prefer-with
  namespace: demo
spec:
  version: "4.4.26"
  terminationPolicy: WipeOut
  replicas: 1
  # replicaSet:
  #   name: "rs"
  # sslMode: requireSSL
  sslMode: preferSSL
  tls:
    issuerRef:
      apiGroup: "cert-manager.io"
      kind: Issuer
      name: mongo-ca-issuer
  # clusterAuthMode: x509
  configSecret:
    name: mg-configuration
  podTemplate:
    spec:
      # nodeSelector:
      #   node.kubernetes.io/instance-type: g6-standard-2
      # tolerations:
      # - key: nodepool
      #   value: medium
      #   effect: NoSchedule
      resources:
        requests:
          "cpu": "0.5"
          "memory": 500Mi
        limits:
          "cpu": "2"
          "memory": 3900Mi
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

# recommender/input/cluster_feeder.go -> updatePodMemory() -> pod.Containers[i] = cnt
# go wait.Until(c.Recommender.RunOnce, c.Opts.MetricsFetcherInterval, stopCh)
# for {c.Recommender.RunOnce(); time.Sleep(c.Opts.MetricsFetcherInterval) }


# allowConnectionsWithoutCertificates
