apiVersion: node.k8s.appscode.com/v1alpha1
kind: NodeTopology
metadata:
  name: lke-pools
spec:
  nodeSelectionPolicy: LabelSelector
  topologyKey: "node.kubernetes.io/instance-type"
  nodeGroups: # capacities here are actually slightly less than the allocatable resources.
  - topologyValue: g6-standard-1
    capacity:
      cpu: 950m
      memory: 1.9Gi
  - topologyValue: g6-standard-2
    capacity:
      cpu: 1950m
      memory: 3.9Gi
  - topologyValue: g6-standard-4
    capacity:
      cpu: "3.9"
      memory: 8Gi
  - topologyValue: g6-standard-6
    capacity:
      cpu: "5.8"
      memory: 16Gi


# g6-standard-1
#     allocatable:
#       cpu: "1"
#       ephemeral-storage: "47484676837"
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 1930764Ki
#       pods: "110"
#     capacity:
#       cpu: "1"
#       ephemeral-storage: 51524172Ki
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 2033164Ki
#       pods: "110"
# g6-standard-2
#     allocatable:
#       cpu: "2"
#       ephemeral-storage: "76019768399"
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 3925900Ki
#       pods: "110"
#     capacity:
#       cpu: "2"
#       ephemeral-storage: 82486728Ki
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 4028300Ki
#       pods: "110"
# g6-standard-4
#     allocatable:
#       cpu: "4"
#       ephemeral-storage: "152115318123"
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 8048008Ki
#       pods: "110"
#     capacity:
#       cpu: "4"
#       ephemeral-storage: 165055684Ki
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 8150408Ki
#       pods: "110"
# g6-standard-6
#     allocatable:
#       cpu: "6"
#       ephemeral-storage: "304306417570"
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 16292760Ki
#       pods: "110"
#     capacity:
#       cpu: "6"
#       ephemeral-storage: 330193596Ki
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 16395160Ki
#       pods: "110"
