apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bytebuilders
    app.kubernetes.io/name: bytebuilders-bind
  name: bytebuilders-bind
  namespace: bb
spec:
  # clusterIP: 10.128.102.211
  # clusterIPs:
  # - 10.128.102.211
  # externalTrafficPolicy: Cluster
  # internalTrafficPolicy: Cluster
  # ipFamilies:
  # - IPv4
  # ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32375
    port: 80
    protocol: TCP
    targetPort: 3003
  selector:
    app.kubernetes.io/instance: bytebuilders
    app.kubernetes.io/name: bytebuilders-bind
  sessionAffinity: None
  type: NodePort
