apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: rotate
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef:
    name: sh4
  tls:
    # remove: true
    # issuerRef:
    #   name: mongo-ca-issuer
    #   kind: Issuer
    #   apiGroup: "cert-manager.io"
    rotateCertificates: true