apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: se
  namespace: demo
spec:
  mongodb:
    databaseRef:
      name: mg
      namespace: demo
    pluginName: mongodb-database-plugin
  vaultRef:
    name: vault
    namespace: vv