apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: mg-as-sh
  namespace: demo
spec:
  databaseRef:
    name: single
  storage:
    standalone:
      trigger: "On"
      usageThreshold: 60
      scalingThreshold: 50