# kubectl create secret generic -n demo new-custom-config --from-file=./mongod.conf

apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: up2
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: mg4
  verticalScaling:
    replicaSet:
      resources: {}
      #   requests:
      #     memory: "900Mi"
      #     cpu: "0.9"
      #   limits:
      #     memory: "900Mi"
      #     cpu: "0.9"
  #     nodeSelectionPolicy: Taint  # Or LabelSelector
  #     topology:
  #       key: nodepool
  #       value: medium
  # configuration:
  #   replicaSet:
  #     configSecret:
  #       name: new-custom-config
  timeout: 5m
  apply: Always


  # https://hooks.slack.com/services/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