# kubectl create secret generic -n demo new-custom-config --from-file=./mongod.conf

apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: up
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: mg6
  verticalScaling:
    replicaSet:
      resources:
        requests:
          memory: "800Mi"
          cpu: "0.8"
        limits:
          memory: "900Mi"
          cpu: "0.9"
  #     nodeSelectionPolicy: Taint  # Or LabelSelector
  #     topology:
  #       key: nodepool
  #       value: medium
  # configuration:
  #   replicaSet:
  #     configSecret:
  #       name: new-custom-config
  timeout: 5m
  apply: Always