apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: mg-backup
  namespace: demo
spec:
  schedule: "*/2 * * * *"
  task:
    name: mongodb-backup-3.6.13
  repository:
    name: lke
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mg
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true